services:
  # app:
  #   build: .
  #   image: "fan9704/escheduler-backend"
  #   container_name: "eschedulerbackend"
  #   ports:
  #     - "0.0.0.0:8000:8000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - prometheus
  #     - loki
  #   networks:
  #     - app_net
  postgres:
    image: "postgres:13"
    container_name: "escheduler-postgresql"
    ports:
      - "0.0.0.0:5432:5432"
    env_file: .env
    networks:
      - app_net
    volumes:
      - "./postgres-data:/var/lib/postgresql/data"
    restart: always
  pgadmin:
    image: "dpage/pgadmin4:latest"
    container_name: escheduler-pgAdmin
    env_file: .env
    ports:
      - "9101:80"
    links:
      - "postgres:pgadmin"
    networks:
      - app_net
    volumes:
     - "./pgadmin_data:/var/lib/pgadmin"
    restart: always
  prometheus:
    image: prom/prometheus
    container_name: escheduler-prometheus
    hostname: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitor
  alertmanager:
    image: prom/alertmanager
    container_name: escheduler-alertmanager
    hostname: alertmanager
    restart: always
    ports:
      - "9093:9093"
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    container_name: escheduler-grafana
    hostname: grafana
    ports:
      - "3001:3000"
    networks:
      - monitor
    volumes:
      - ./grafana_data/data:/var/lib/grafana
      - ./grafana_data/provisioning:/etc/grafana/provisioning

  loki:
    image: grafana/loki:latest
    container_name: escheduler-loki
    ports:
      - "3100:3100"
    networks:
      - monitor
  rabbitmq:
    image: rabbitmq:3.9.10-management
    hostname: rabbitmq
    container_name: escheduler-rabbitmq
    env_file: .env
    restart: always
    ports:
      - "5672:5672" # AMQP protocol
      - "15672:15672" # Management UI

networks:
    monitor:
        driver: bridge
    app_net:
        driver: bridge